version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    volumes:
      - ./mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/default.conf:/etc/nginx/default.conf
      - ./wordpress:/var/www/html
    depends_on:
      - php-fpm

  prometheus:
    image: prom/prometheus:latest
    container_name: prom
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    command: ["-nginx.scrape-uri=http://nginx:80/metrics"]
    
 blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    volumes:
      - ./config/blackbox.yml:/etc/blackbox/blackbox.yml

  prometheus-mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    ports:
      - 9104:9104
    volumes:
      - ./config/my.cnf:/opt/mysqlconf/my.cnf
    command:
      - "--config.my-cnf=/opt/mysqlconf/my.cnf"
    environment:
      DATA_SOURCE_NAME: "exampleuser:examplepassword@(mysql:3306)/exampledb"
