global:
  scrape_interval: 5s
scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: mysql-exporter
    static_configs:
      - targets:
          - 'localhost:9104'

  - job_name: blackbox
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - '192.168.228.31:8080'
        labels:
          service: wordpress
      - targets:
          - '192.168.228.31:80'
        labels:
          service: nginx

    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.228.31:9115
